#!/usr/bin/env bash

set -eu

# where the scripts will run are located
scriptDirectory='/sutherland-scratch/rc845/Vallier/NAFLD-Gribben/4.Analysis/9.Cell-Cell-Interaction/1.CellPhoneDB/Scripts/'

# where the seurat input .rds files are
inDirectory='/sutherland-scratch/rc845/Vallier/NAFLD-Gribben/4.Analysis/9.Cell-Cell-Interaction/1.CellPhoneDB/seuratObjects/'
inStem=$1 #'Chol-c3,7,22_vs_AllCells_endStage' # name of in seurat file, without .rds
cellTypeCol='CellPhoneComp' # name of metadata column with cellType annotation

# where the (intermediate) exported matrices and metadata will be written to
DBInDirectory='/sutherland-scratch/rc845/Vallier/NAFLD-Gribben/4.Analysis/9.Cell-Cell-Interaction/1.CellPhoneDB/4.By-Disease-status/1.CellPhoneDB-Input-'${inStem}'/'
# where the final cellphonedb output will be written to
DBOutDirectory='/sutherland-scratch/rc845/Vallier/NAFLD-Gribben/4.Analysis/9.Cell-Cell-Interaction/1.CellPhoneDB/4.By-Disease-status/2.CellPhoneDB-Output-'${inStem}'/'


sampleName='sample'


mkdir -p ${DBInDirectory}
mkdir -p ${DBOutDirectory}


cd ${scriptDirectory}

inFile=${inDirectory}${inStem}.rds

### extract the metadata and count data from the seurat object
#echo "commented out R extraction for now..."
Rscript ./1.Export-Matrix-and-Metadata-Seurat-CellPhoneDB_sparse.R \
--input_seurat ${inFile} \
--annot ${cellTypeCol} \
--assay_name SCT \
--output_path ${DBInDirectory} \
--sample_name ${sampleName}


### use the extracted files to run cellphonedb

# paths to the files generated by 1.xxx, and used by 3.xxx
meta_data=${DBInDirectory}${sampleName}-Annot-${cellTypeCol}.txt
counts_dir=${DBInDirectory}${sampleName}/
# path to cellPhoneDB output - I think is just a directory...

echo "cellphoneDB input:"
echo ${meta_data}
echo ${counts_dir}

./run_CellPhoneDB.sh \
${counts_dir} \
${meta_data} \
${DBOutDirectory}${sampleName}
